[server]
# do not use when running server with docker
port = 8080
# optional
admin_api = "/admin"
allow_new_register = true

# examples: 256 kB, 0.500 mib, 1MB, 1GiB
[server.limits]
json = "4MiB"

[db]
# sqlite
url = "data.db"

# mysql
name = "kotatsu_db"
host = "localhost"
port = 3306
user = "YOUR_USER"
password = "YOUR_PASSWORD"

[jwt]
secret = ""
issuer = "http://0.0.0.0:8080/"
audience = "http://0.0.0.0:8080/resource"
