services:
  test-db:
    image: mariadb:lts
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: asdf
      MARIADB_DATABASE: kotatsu_db_test
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    volumes:
      - db_data:/var/lib/mariadb
    ports:
      - "3307:3306"

volumes:
  db_data:
