services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_USER: USER
      MARIADB_PASSWORD: PASSWORD
      MARIADB_DATABASE: kotatsu_db
      MARIADB_ROOT_PASSWORD: ROOT_PASSWORD
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      # socket
      - /run/mysqld:/run/mysqld
    expose:
      - 3306
    networks:
      internal:
        ipv4_address: 172.20.0.2

  # server with mysql
  server-mysql:
    # if you want to work with original database, change "-mysql" to "-original"
    image: ghcr.io/istudyatuni/kotync:VERSION-mysql
    container_name: kotync-original
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: USER
      DATABASE_PASSWORD: PASSWORD
      DATABASE_NAME: kotatsu_db
      JWT_SECRET: SECRET
      ALLOW_NEW_REGISTER: true
      # ADMIN_API: /ADMIN
      # LIMITS_JSON: 4MiB
      # RUST_LOG: info
    ports:
      - 8081:8080
    restart: always
    networks:
      internal:
        # to be able to tell mariadb IP of client
        ipv4_address: 172.20.0.3

  # server with sqlite
  server:
    image: ghcr.io/istudyatuni/kotync:VERSION
    container_name: kotync
    environment:
      DATABASE_URL: /app/data/data.db
      JWT_SECRET: SECRET
      ALLOW_NEW_REGISTER: true
      # ADMIN_API: /ADMIN
      # LIMITS_JSON: 4MiB
      # RUST_LOG: info
    ports:
      - 8081:8080
    volumes:
      # change ${PWD} to directory, where you want to save data.db
      - ${PWD}:/app/data
    restart: always

# https://stackoverflow.com/a/39498534
networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
