name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/check.yaml
      - Cargo.lock
      - migrations/**
      - src/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: '1.81'
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just ci
