name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/check.yaml
      - Cargo.lock
      - migrations/**
      - src/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.78
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --no-default-features --features=new
      - run: cargo fmt --check
      - run: cargo test --no-default-features --features=new
