name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/check.yaml
      - Cargo.lock
      - migrations/**
      - src/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.88'
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: install tools
        run: nix profile add "nixpkgs#just" && just -V

      - run: just ci
