name: Build docker:dev

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - .github/workflows/docker-dev.yaml
  #     - Cargo.lock
  #     - Dockerfile
  #     - migrations/**
  #     - src/**

permissions:
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/docker-build.yaml
    with:
      tag: dev
