name: Build docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Name of tag, e.g. 1.0"
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Name of tag, e.g. 1.0"
        required: true
        type: string

permissions:
  packages: write

env:
  IMAGE_NAME: ghcr.io/istudyatuni/kotync
  IMAGE_TAG: ${{ inputs.tag }}
  ORIGINAL_TAG: ${{ inputs.tag }}-original

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker
        run: |
          docker build . --tag $IMAGE_NAME:$IMAGE_TAG
          docker build . --tag $IMAGE_NAME:$ORIGINAL_TAG --build-arg kind=original
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker
        run: |
          docker push $IMAGE_NAME:$ORIGINAL_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG
