name: Build docker:dev

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - .github/workflows/docker-dev.yaml
  #     - Cargo.lock
  #     - Dockerfile
  #     - migrations/**
  #     - src/**

env:
  IMAGE_NAME: ghcr.io/istudyatuni/kotync
  IMAGE_TAG: dev
  ORIGINAL_TAG: dev-original

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker
        run: |
          docker build . --tag $IMAGE_NAME:$IMAGE_TAG
          docker build . --tag $IMAGE_NAME:$ORIGINAL_TAG --build-arg kind=original
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker
        run: |
          docker push $IMAGE_NAME:$ORIGINAL_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG
